### ISSUE TITLE
vmx build on os x

### ISSUE THREAD

**Issue by htj** [plajjan/vrnetlab#164]
Hi

I'm trying to build/run vmx on os x, but have run into some issues. Using vmx-15.1F4.15.tgz

First issue:

../makefile-install.include:30: warning: overriding commands for target `docker-pre-build'
../makefile.include:18: warning: ignoring old commands for target `docker-pre-build'
Makefile:22: warning: overriding commands for target `docker-build-image-copy'
../makefile.include:21: warning: ignoring old commands for target `docker-build-image-copy'
for IMAGE in vmx-15.1F4.15.tgz; do \
		echo "Making $IMAGE"; \
		/Library/Developer/CommandLineTools/usr/bin/make IMAGE=$IMAGE docker-build; \
	done
Making vmx-15.1F4.15.tgz
../makefile-install.include:30: warning: overriding commands for target `docker-pre-build'
../makefile.include:18: warning: ignoring old commands for target `docker-pre-build'
Makefile:22: warning: overriding commands for target `docker-build-image-copy'
../makefile.include:21: warning: ignoring old commands for target `docker-build-image-copy'
rm -f docker/*.qcow2* docker/*.tgz* docker/*.vmdk* docker/*.iso
cat cidfile | xargs --no-run-if-empty docker rm -f
cat: cidfile: No such file or directory
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
make[1]: [docker-pre-build] Error 1 (ignored)
rm cidfile
rm: cidfile: No such file or directory
make[1]: [docker-pre-build] Error 1 (ignored)
docker tag vr-vmx:vmx-15.1F4.15.tgz vr-vmx:vmx-15.1F4.15.tgz-previous-build
Error response from daemon: No such image: vr-vmx:vmx-15.1F4.15.tgz
make[1]: [docker-pre-build] Error 1 (ignored)
ERROR: Incorrect version string (vmx-15.1F4.15.tgz)
make[1]: *** [docker-build-common] Error 1
make: *** [docker-image] Error 2

It seems the VERSION is not being set correctly. Echoing it out, it is identical to the file name.

The following patch seems to fix it:

diff --git a/vmx/Makefile b/vmx/Makefile
index 9af9915..7a68c97 100644
--- a/vmx/Makefile
+++ b/vmx/Makefile
@@ -12,7 +12,7 @@ IMAGE_GLOB=*.tgz
 # vmx-bundle-17.1R1.8.tgz
 # vmx-bundle-16.1R4-S2.2.tgz
 # vmx-bundle-17.1R1-S1.tgz
-VERSION=$(shell echo $(IMAGE) | sed -e 's/.\+[^0-9]\([0-9][0-9]\.[0-9][A-Z][0-9]\+\(\.[0-9]\+\|-S[0-9]\+\(\.[0-9]\+\)\?\)\)[^0-9].*$$/\1/')
+VERSION=$(shell echo $(IMAGE) | sed 's/^vmx-//' | sed 's/^vmx-bundle-//' | sed 's/.tgz$$//' )

 -include ../makefile-sanity.include
 -include ../makefile.include

I'm not entirely sure this is the wanted behaviour (because I cannot understand the orginal regex :-))

The I run into this:

Making vmx-15.1F4.15.tgz
../makefile-install.include:30: warning: overriding commands for target `docker-pre-build'
../makefile.include:18: warning: ignoring old commands for target `docker-pre-build'
Makefile:22: warning: overriding commands for target `docker-build-image-copy'
../makefile.include:21: warning: ignoring old commands for target `docker-build-image-copy'
rm -f docker/*.qcow2* docker/*.tgz* docker/*.vmdk* docker/*.iso
cat cidfile | xargs --no-run-if-empty docker rm -f
cat: cidfile: No such file or directory
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
make[1]: [docker-pre-build] Error 1 (ignored)
rm cidfile

The  --no-run-if-empty isn't supported on the ancient bsd utils in os x. The build continues quite some time after this, so maybe some error checking would be good here. I tried this:

diff --git a/vmx/vmx-extract.sh b/vmx/vmx-extract.sh
index 6c35bdf..1730bf6 100755
--- a/vmx/vmx-extract.sh
+++ b/vmx/vmx-extract.sh
@@ -5,7 +5,7 @@ IMAGE=$1
 echo "Extracting Juniper vMX tgz"
 rm -rf tmp docker/vmx
 mkdir -p tmp docker/vmx
-tar -zxvf ${IMAGE} -C tmp/ --wildcards vmx*/images/*img --wildcards vmx*/images/*qcow2
+tar -zxvf ${IMAGE} -C tmp/ --wildcards vmx*/images/*img --wildcards vmx*/images/*qcow2 || (echo "error untarring" ; exit 1 )
 mv -v tmp/vmx*/images/vmxhdd.img docker/vmx/
 mv -v tmp/vmx*/images/junos-vmx*qcow2 docker/vmx/              # 16.1 and newer
 mv -v tmp/vmx*/images/jinstall64-vmx*img docker/vmx/

But it was ignored by the caller :-/

I tried removing the --wildcards:

diff --git a/vmx/vmx-extract.sh b/vmx/vmx-extract.sh
index 6c35bdf..e92df82 100755
--- a/vmx/vmx-extract.sh
+++ b/vmx/vmx-extract.sh
@@ -5,7 +5,7 @@ IMAGE=$1
 echo "Extracting Juniper vMX tgz"
 rm -rf tmp docker/vmx
 mkdir -p tmp docker/vmx
-tar -zxvf ${IMAGE} -C tmp/ --wildcards vmx*/images/*img --wildcards vmx*/images/*qcow2
+tar -zxvf ${IMAGE} -C tmp/ vmx*/images/*img vmx*/images/*qcow2
 mv -v tmp/vmx*/images/vmxhdd.img docker/vmx/
 mv -v tmp/vmx*/images/junos-vmx*qcow2 docker/vmx/              # 16.1 and newer
 mv -v tmp/vmx*/images/jinstall64-vmx*img docker/vmx/

This seems to work. At least the build takes a long time :-)

It doesn't start though, looking into that :-)

For now, I've put the patches here:
https://github.com/NORDUnet/vrnetlab/tree/vmx_osx

**Comment by htj** [comment]
This is the failure when starting vmx:

`
2017-10-25 12:47:10,974: vrnetlab   INFO     STDOUT:
2017-10-25 12:47:10,979: vrnetlab   INFO     STDERR:
2017-10-25 12:47:10,980: vrnetlab   ERROR    Telnet session was disconncted, restarting
Traceback (most recent call last):
  File "/launch.py", line 308, in <module>
    vr.start()
  File "/vrnetlab.py", line 297, in start
    vm.work()
  File "/vrnetlab.py", line 240, in work
    self.restart()
  File "/vrnetlab.py", line 205, in restart
    self.stop()
  File "/vrnetlab.py", line 198, in stop
    self.p.communicate(timeout=10)
  File "/usr/lib/python3.5/subprocess.py", line 801, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1437, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/usr/lib/python3.5/selectors.py", line 351, in register
    key = super().register(fileobj, events, data)
  File "/usr/lib/python3.5/selectors.py", line 237, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/usr/lib/python3.5/selectors.py", line 224, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/lib/python3.5/selectors.py", line 39, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.TextIOWrapper name=3 encoding='ANSI_X3.4-1968'>
`

Any ideas here?

**Comment by plajjan** [comment]
This cannot work. docker on os x is actually using a virtual linux machine. xhyve is the hypervisor used on OS X to run that linux VM. xhyve does not support nested virtualization. vrnetlab requires KVM and since that's not available it cannot work :(

**Comment by plajjan** [comment]
There might be errors in makefiles etc due to BSD make vs GNU make or some such but I think that's largely irrelevant given that you can't run it in the end anyway!?

**Comment by htj** [comment]
Doh. Thanks for the explanation.

The errors are defintely due to gnu/bsd differences.

I still think the VERSION regex is worth merging :-) (assuming it is correct)

**Comment by plajjan** [comment]
I don't think there's anything wrong with the VERSION regex or at least I don't see it based on this output. Instead of making assumptions on the filename, like vmx or vmx-bundle, it looks for the version number, like 17.1R1.8 and extracts that. It also allows some other forms which is why it might look a little complex ;)
