### ISSUE TITLE
question: Can i put virtual router at internet?

### ISSUE THREAD

**Issue by jjjan** [plajjan/vrnetlab#179]
Hello,
is it possible to put virtual router at internet as real router and monitoring it? 
i mean set valid ip for virtual router?

**Comment by htj** [comment]
Hi

So vMX from Juniper and vEOS from Arista are both sold without hardware, as software based routing solutions. So yes, certainly.

However, the purpose of vrnetlab is more about being able to build a lab setup with virtual routers.

**Comment by plajjan** [comment]
I think the question is answered. Yes, it's possible. Perhaps not optimal with vrnetlab for a bunch of reasons. Since there's no followup question I'm closing.
