### ISSUE TITLE
vr-xcon fails with openwrt

### ISSUE THREAD

**Issue by blinklet** [plajjan/vrnetlab#190]
I am just getting started with vrnetlab. Following the instructions in the README file, I created an openwrt image, then created two openwrt containers and tried to connect each one to each other. The link setup fails with a syntax error. What am I doing wrong?

1) Create two containers:
```
# docker run -d --privileged --name openwrt1 vrnetlab/vr-openwrt:18.06.2
# docker run -d --privileged --name openwrt2 vrnetlab/vr-openwrt:18.06.2
```

2) Create a link between them (port 1 on each)
```
# docker run -d --privileged --name vr-xcon vrnetlab/vr-xcon:latest --link openwrt1 --link openwrt2 vr-xcon --p2p openwrt1/1--openwrt2/1
```

3) Logs show the following error:
```
# docker logs vr-xcon
usage: xcon.py [-h] [--debug] [--p2p P2P [P2P ...]] [--raw-listen RAW_LISTEN]
               [--raw-if RAW_IF] [--tap-listen TAP_LISTEN] [--tap-if TAP_IF]
               [--ipv4-address IPV4_ADDRESS] [--ipv4-route IPV4_ROUTE]
               [--ipv6-address IPV6_ADDRESS] [--ipv6-route IPV6_ROUTE]
               [--vlan VLAN] [--trace]
xcon.py: error: unrecognized arguments: --link openwrt1 --link openwrt2 vr-xcon
```

System info:
```
# docker --version
Docker version 18.09.3, build 774a1f4
# uname -ar
Linux Docker 4.18.0-1011-azure #11~18.04.1-Ubuntu SMP Fri Feb 15 18:56:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by blinklet** [comment]
I am using Ubuntu 18.04 Server.

**Comment by blinklet** [comment]
Additional info:
I tried running vrnetlab on Ubuntu 16.04 with Docker engine 1.13.1. I still see the same problem.

**Comment by emjemj** [comment]
You need to put the --link statements before the image name since its an argument to docker, not vr-xcon.

**Comment by blinklet** [comment]
Thanks. The following worked for me:

docker run -d --privileged --name vr-xcon --link openwrt1 --link openwrt2 vrnetlab/vr-xcon:latest --p2p openwrt1/1--openwrt2/1
