### ISSUE TITLE
Cisco XR 5.3.3

### ISSUE THREAD

**Issue by job** [plajjan/vrnetlab#22]
Something goes wrong with configuring the initial user & logging in with IOS 5.3.3. This does work  for 5.3.1 and 6.0.1

Let me know if you dont have 5.3.3 and need me to provide logs

**Comment by plajjan** [comment]
It works fine with the demo 5.3.3 that you can get from https://upload.cisco.com/cgi-bin/swc/fileexg/main.cgi?CONTYPES=Cisco-IOS-XRv. Are you perhaps using a production version image?

Right now we are relying on the admin/admin account that is pre-created in the Cisco demo images... should fix that.

**Comment by job** [comment]
That might be it. I'm downloading iosxrv-k9-demo.vmdk-5.3.3 from the file exchange and will report back whether I still have that issue

**Comment by plajjan** [comment]
I created #23 for tracking the credentials issue. With it fixed you should be able to use whichever image.
