### ISSUE TITLE
vMX 17.4R1.16 vr-xcon is not working

### ISSUE THREAD

**Issue by kalmanoharan** [plajjan/vrnetlab#225]
Hello Kristian,
I am new to vrnetlab and exploring it to setup a small Juniper MX topology. I managed to setup vMX 17.4R1.16 with your documentations and it worked perfectly.
Now I got two VMX devices running as containers. I would like to connect them together and test a ping between them. I used vr-xcon based on your documentation. But for some-reason its not working as expected. I am not seeing any logs either with `docker logs -f vr-xcon`.
I tried doing a local make for vr-xcon container as well as download the ones from docker hub. Both didn't worked for me.

Not sure what I am missing here.
Looking for your help to see what I am missing here.

I believe the following command will connect MX1 ge-0/0/0 with MX2 ge-0/0/0 but its working :(

```docker run -d --privileged --name vr-xcon --link MX1 --link MX2 vr-xcon --p2p MX1/1--MX2/1 --debug``` 

Here are some of my logs.

```root@nel17-lab1-vagrantserver1:/home/kalmanoharan/vrnetlab# docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                   PORTS                                                 NAMES
bb688580a3e5        vr-xcon                     "/xcon.py --p2p MX1/…"   30 seconds ago      Up 30 seconds                                                                  vr-xcon
5c34476960c6        vrnetlab/vr-vmx:17.4R1.16   "/launch.py"             8 minutes ago       Up 8 minutes (healthy)   22/tcp, 830/tcp, 5000/tcp, 10000-10099/tcp, 161/udp   MX2
2ae7a8b77d56        vrnetlab/vr-vmx:17.4R1.16   "/launch.py"             8 minutes ago       Up 8 minutes (healthy)   22/tcp, 830/tcp, 5000/tcp, 10000-10099/tcp, 161/udp   MX1

root@nel17-lab1-vagrantserver1:/home/kalmanoharan/vrnetlab# docker logs -f vr-xcon```

```root@MX1# run show interfaces terse | match inet
ge-0/0/0.0              up    up   inet     192.168.1.1/30
pfe-0/0/0.16383         up    up   inet
                                   inet6
pfh-0/0/0.16383         up    up   inet
pfh-0/0/0.16384         up    up   inet
ge-0/0/1.0              up    up   inet     192.168.2.1/30
em1.0                   up    up   inet     10.0.0.4/8
                                   inet6    fe80::5254:ff:fe4b:6401/64
fxp0.0                  up    up   inet     10.0.0.15/24
jsrv.1                  up    up   inet     128.0.0.127/2
lo0.16384               up    up   inet     127.0.0.1           --> 0/0
lo0.16385               up    up   inet

[edit]
root@MX1# run ping 192.168.1.2
PING 192.168.1.2 (192.168.1.2): 56 data bytes
^C
--- 192.168.1.2 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss

[edit]
root@MX1# run ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: icmp_seq=0 ttl=64 time=0.051 ms
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=0.053 ms
^C
--- 192.168.1.1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.051/0.052/0.053/0.001 ms

[edit]
root@MX1#```

```root@MX2# run show interfaces terse | match inet
ge-0/0/0.0              up    up   inet     192.168.1.2/30
pfe-0/0/0.16383         up    up   inet
                                   inet6
pfh-0/0/0.16383         up    up   inet
pfh-0/0/0.16384         up    up   inet
ge-0/0/1.0              up    up   inet     192.168.2.2/30
em1.0                   up    up   inet     10.0.0.4/8
                                   inet6    fe80::5254:ff:fe54:8d01/64
fxp0.0                  up    up   inet     10.0.0.15/24
jsrv.1                  up    up   inet     128.0.0.127/2
lo0.16384               up    up   inet     127.0.0.1           --> 0/0
lo0.16385               up    up   inet

[edit]
root@MX2# run ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1): 56 data bytes
^C
--- 192.168.1.1 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

[edit]
root@MX2#```

**Comment by plajjan** [comment]
It's quite common with interface mismatch problems on MX. Try `docker run -d --privileged --name vr-xcon --link MX1 --link MX2 vr-xcon --p2p MX1/2--MX2/2 --debug` to see if it works (I used interface 2 instead of 1 for vr-xcon). You should still configure ge-0/0/0 on the MX. If that works, the startup script needs to have an exception for this JUNOS version (there's already a list of versions which we treat differently).

Alternatively, try with the vr-xcon command you are using now (interface 1) but configure ge-0/0/1 on the device. I actually see you put 192.168.2.0/30 on there but didn't show if it works or not. This would cover if the mismatch is in the other direction (IIRC this shouldn't be the case, but I'd have to read the code + test to know).

**Comment by kalmanoharan** [comment]
Thanks @plajjan  for the quick response.
Yes the port mapping is the issue. I tried `docker run -d --privileged --name vr-xcon --link MX1 --link MX2 vr-xcon --p2p MX1/2--MX2/2 --debug` and it worked like a charm.


```
root@MX1# run show lldp neighbors
Local Interface    Parent Interface    Chassis Id          Port info          System Name
ge-0/0/0           -                   2c:6b:f5:74:70:c0   ge-0/0/0           MX2

[edit]
root@MX1# run ping 192.168.1.2
PING 192.168.1.2 (192.168.1.2): 56 data bytes
64 bytes from 192.168.1.2: icmp_seq=0 ttl=64 time=3.784 ms
64 bytes from 192.168.1.2: icmp_seq=1 ttl=64 time=3.649 ms
^C
--- 192.168.1.2 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 3.649/3.716/3.784/0.068 ms
```

**Comment by plajjan** [comment]
@kalmanoharan see https://github.com/plajjan/vrnetlab/blob/master/vmx/docker/launch.py#L194 - if you add your version in that list, this will be fixed by building the images with a correct offset (by adding another dummy interface). Please test that. If it works, could you submit a PR?

**Comment by kalmanoharan** [comment]
Thanks Kristian !!
I tested this and it works.
Created a PR request to you.
https://github.com/plajjan/vrnetlab/pull/227
