### ISSUE TITLE
Ability to use any Traffic Generators in vrnetlab Topologies(Juniper)

### ISSUE THREAD

**Issue by kalmanoharan** [plajjan/vrnetlab#243]
Hi @plajjan and Team ,
Thanks for putting this awesome project. I am really enjoying it. I feel it would be a great value if we the ability to use any Traffic Generators like iperf inside vrnetlab topologies to pump traffic for learn some of the MPLS LSP re-routing scenarios,etc.
my thought is that may be attach a ubuntu container to the vrnetlab MX1 interface using vbridge and then same other ends. Pump traffic using iperf. Not sure how to attach a container network to MX1 any interface.
Is it possible with Vrnetlab ? If so can you please share any documents or steps to achieve this.

**Comment by plajjan** [comment]
Hi, yes, sure, that's possible. vrnetlab uses its own overlay network, so you need the vr-xcon program running in your container (or some intermediary container) to connect to the overlay. The vr-bgp container does exactly this. Start by trying it out, you can just ping the other boxes or install something into the vr-bgp container, like iperf, to generate traffic.

Once you've understood how vr-xcon is applied in vr-bgp, you can do the same to your own container, or to a container built elsewhere.
