### ISSUE TITLE
Add HP VSR1000

### ISSUE THREAD

**Issue by plajjan** [plajjan/vrnetlab#35]
Dunno for what really.. for the lulz!?

https://h10145.www1.hp.com/Downloads/SoftwareReleases.aspx?ProductNumber=JG811AAE&lang=en&cc=us&prodSeriesId=5443163

**Comment by holmahenkel** [comment]
One for the lulz attempt here https://github.com/plajjan/vrnetlab/pull/128 :-)

**Comment by holmahenkel** [comment]
Take two https://github.com/plajjan/vrnetlab/pull/129

**Comment by plajjan** [comment]
This is now fixed, roughly by taking the changeset of #129 and then doing a few things differently and manually merging it.
