### ISSUE TITLE
vmx failed vfpc boot

### ISSUE THREAD

**Issue by plajjan** [plajjan/vrnetlab#44]
Seeing this on the vfpc serial port (5001):
```

mount: mounting /dev/sda2 on /mnt failed: No such file or directory
Waiting for root device to be ready...
```
it just keeps repeating forever. This is from a run with many virtual routers. If I run a single vMX on my laptop it works fine so I suspect this is somehow load related... :/

It's vMX 15.1F6.9 - maybe try 16.1 ?

**Comment by Yuvaraj89888** [comment]
My vMX FP is not starting giving error
md: linear personality registered for level -1
tsc: Refined TSC clocksource calibration: 1896.012 MHz
md: raid0 personality registered for level 0
md: raid1 personality registered for level 1
md: raid10 personality registered for level 10
md: multipath personality registered for level -4
md: faulty personality registered for level -5
device-mapper: ioctl: 4.24.0-ioctl (2013-01-15) initialised: dm-devel@redhat.com
cpuidle: using governor ladder
usbcore: registered new interface driver usbhid
usbhid: USB HID core driver
u32 classifier
    Actions configured
nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
TCP: cubic registered
NET: Registered protocol family 10
sit: IPv6 over IPv4 tunneling driver
NET: Registered protocol family 17
9pnet: Installing 9P2000 support
Key type dns_resolver registered
rtc_cmos 00:00: setting system clock to 2020-08-05 11:01:37 UTC (1596625297)
ALSA device list:
  No soundcards found.
Freeing unused kernel memory: 1268k freed
Write protecting the kernel read-only data: 14336k
Freeing unused kernel memory: 1304k freed
Freeing unused kernel memory: 488k freed
mount: mounting /dev/sda2 on /mnt failed: No such file or directory
Waiting for root device to be ready...
input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input2
mount: mounting /dev/sda2 on /mnt failed: No such file or directory
Waiting for root device to be ready...
mount: mounting /dev/sda2 on /mnt failed: No such file or directory
Waiting for root device to be ready...
mount: mounting /dev/sda2 on /mnt failed: No such file or directory
Waiting for root device to be ready...
mount: mounting /dev/sda2 on /mnt failed: No such file or directory
Waiting for root device to be ready...
mount: mounting /dev/sda2 on /mnt failed: No such file or directory
Waiting for root device to be ready...
mount: mounting /dev/sda2 on /mnt failed: No such file or directory
Waiting for root device to be ready...
mount: mounting /dev/sda2 on /mnt failed: No such file or directory
Waiting for root device to be ready...
mount: mounting /dev/sda2 on /mnt failed: No such file or directory
Waiting for root device to be ready...
