### ISSUE TITLE
How about networking ? 

### ISSUE THREAD

**Issue by ezobn** [plajjan/vrnetlab#74]
It is really good, what you are doing here ... But I have the question. Do you use this docker containers running KVM with routers to connect them into segment of network  ? To run IGP,BGP,MPLS  ? I am currently using OpenStack Neutron for this. But looking currently to use LXC/LXD containers managed by Nova and Neutron for networking for this... https://www.enog.org/presentations/enog-9/15-FOSSinTelecom-ENOG9-v3.pdf

**Comment by plajjan** [comment]
Yes, vr-xcon is the process/container that is used to connect two or more vrnetlab routers with each other. It is a bit special in that it's using a rather exotic networking concept of qemu, namely exposing the router interfaces as TCP sockets. vr-xcon is the process that connects two of these TCP sockets with each other. There are some slick advantages to this, primarily that it allows us to define the topology between routers after they have been started, which is much more difficult with docker default networking or Linux bridges.

There is a `--tap-listen` argument to vr-xcon which can be used to bridge a vrnetlab router to a normal docker container. Have you read https://github.com/plajjan/vrnetlab/blob/master/vr-xcon/README.md ?

I don't know enough about Neutron to comment on how it can be used. vrnetlab was designed not to have dependencies such as the existence of an OpenStack environment to run - it's supposed to be easy to get going with in a simple docker environment :)

I briefly looked through the presentation you linked. I think vrnetlab does/can do the same, i.e. build complex topologies across multiple physical machines.

I am using vrnetlab for testing IGP, BGP etc configuration in DT/TeraStream CI system.

**Comment by ezobn** [comment]
Hi Kristian, 

Somehow missed this README, sorry… I will learn about this, thank you. 

Evgeny
