### ISSUE TITLE
xrv Dockerfile doesnt copy healthcheck.py

### ISSUE THREAD

**Issue by bdreisbach** [plajjan/vrnetlab#84]
here is a patch:

diff --git a/xrv/docker/Dockerfile b/xrv/docker/Dockerfile
index ca8444a..10aa51e 100644
--- a/xrv/docker/Dockerfile
+++ b/xrv/docker/Dockerfile
@@ -15,6 +15,7 @@ RUN apt-get update -qy \

 ARG IMAGE
 COPY $IMAGE /xrv.vmdk
+COPY healthcheck.py /
 COPY vrnetlab.py /
 COPY launch.py /

**Comment by plajjan** [comment]
Thanks! This is fixed through bf273f21791cb45cc9eebfea94c80f71d84a6879
