### ISSUE TITLE
Figure out weird interface mapping and max interfaces on CSR1000v

### ISSUE THREAD

**Issue by plajjan** [plajjan/vrnetlab#91]
Look at the interface mapping table for CSR1000v - https://github.com/plajjan/vrnetlab/tree/master/csr#usage - why is Gi2 mapped to if 10 ? Figure out why!!!

Also, try to see if we can raise the number of interfaces above 10!

**Comment by emjemj** [comment]
It would seem that the weird interface mapping is a hoax, I'll do some more digging. I've gotten the image which supposedly has the weird interface mapping and will try it out. 

No version that I have tried so far has exhibited the interface mapping problem.

**Comment by emjemj** [comment]
It's not a hoax :( Readme has been updated with information about which versions exhibit this interface mapping problem.

**Comment by plajjan** [comment]
This page http://www.cisco.com/c/en/us/td/docs/routers/csr1000/software/configuration/b_CSR1000v_Configuration_Guide/b_CSR1000v_Configuration_Guide_chapter_00.html says that 26 vNICs should be supported on KVM.

I have fiddled quite a lot with other platforms and found that there is usually a limit on around 26 NICs, which is simply because of PCI bus limitations. You can have 32 devices on a bus. Some are reserved and others are used for other controllers, like disk driver etc leaving you with 26 for NICs. For XRv and JUNOS I have worked around this through the use of many PCI buses. I suspect something similar might actually be possible on CSR1000v too.

**Comment by plajjan** [comment]
3.x releases are limited to 10 NICs it seems though. Need to get newer images.

**Comment by plajjan** [comment]
So the 10 NICs are including the mgmt interface. vrnetlab counts NICs + mgmt so we had off by one issue. With #118 this is now fixed, we do 9 NICs + mgmt NIC for a total of 10 and thus the mapping is correct.
