### ISSUE TITLE
latest tag isn't created for vr-vmx image

### ISSUE THREAD

**Issue by htj** [plajjan/vrnetlab#92]
ok, this is really nitpicking, but the documentation says use this to run:

docker run -d --privileged --name my-vmx-router vr-vmx

This is what gets registered duringa build

htj@pyrite:~/src/vrnetlab$ docker images|grep vmx
vr-vmx              15.1F4.15                                               1566b3575f14        2 minutes ago       6.44 GB

So the docker run command doesn't work. Of course, this works fine:

htj@pyrite:~/src/vrnetlab$ docker run -d --privileged --name opennsa-vpls vr-vmx:15.1F4.15

So either add the tag in the makefile or update the documentation.

**Comment by plajjan** [comment]
I think we should update the documentation. It's not clear what "latest" should refer too. I think many from the docker world would assume it's the last built container, so vr-vmx:15.1F4.15 would be "latest" when it was built after vr-vmx:16.1R2.13. I suspect many router jockeys would expect the opposite.

Updating the docs and always using explicit versions of the images is the only sane way to work with this IMHO.

**Comment by emjemj** [comment]
Yes, explicit versions should be required, "latest" means nothing in this context.

**Comment by plajjan** [comment]
@emjemj will you do the needful? =)
